version: '3.1'

services:
  mongo:
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tasks
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - mongonetwork
  app:
    build:
      context: .
    volumes:
      - .:/app
    # links:
    #   - mongo
    ports:
      - '80:5000'
    depends_on:
      - mongo
    networks:
      - mongonetwork
    environment: 
      - PORT=5000
      - JET_LOGGER_MODE=CONSOLE
      - JET_LOGGER_FILEPATH=jet-logger.log
      - JET_LOGGER_TIMESTAMP=TRUE
      - JET_LOGGER_FORMAT=LINE
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - REFRESH_TOKEN_EXPIRES_IN=15d
      - JWT_COOKIE_EXPIRES_IN=90
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
networks:
  mongonetwork:
    driver: bridge
